apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Max-Vassilev/argocd-journey
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{folder.metadata.name}}-argo-application"
    spec:
      project: default
      source:
        repoURL: https://github.com/Max-Vassilev/argocd-journey
        targetRevision: HEAD
        path: "{{folder.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{folder.metadata.name}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
