apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-1
  template:
    metadata:
      labels:
        app: myapp-1
    spec:
      containers:
        - name: myapp
          image: nanajanashia/argocd-app:1.2
          ports:
            - containerPort: 8080
